services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    build: .
    # command: bundle install && bundle exec rails -b '0.0.0.0'
    command: /bin/bash
    volumes:
      - ./rails_app:/app
    ports:
      - "7077:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=db_dev
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
volumes:
  db_data:
